export interface AudioDataInterface  {
  title: string;
  subtext: string;
  duration: string;
  category: string;
  likes: number,
  listens: number,
  description: string
  type: string;
}

const AudioData: Array<AudioDataInterface> = [
  {
    title: "Tranquil Dawn Chorus",
    subtext: "Gentle birdsong for mindful mornings",
    duration: "10:32",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up peacefully with the sounds of the forest.",
    type: "audio",
  },
  {
    title: "Deep Ocean Meditation",
    subtext: "Dive into tranquility with whale song",
    duration: "15:00",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the calming depths of the ocean.",
    type: "audio",
  },
  {
    title: "Floating Among the Clouds",
    subtext: "Ambient music for deep relaxation",
    duration: "22:48",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Drift away with ethereal melodies and soothing harmonies.",
    type: "audio",
  },
  {
    title: "Guided Mindfulness Practice",
    subtext: "Find your center with gentle narration",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Cultivate inner peace through mindful awareness.",
    type: "audio",
  },
  {
    title: "Rainy Afternoon",
    subtext: "Soothing rain sounds",
    duration: "25:12",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of gentle rain.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing water and nature sounds",
    duration: "12:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Listen to the peaceful sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Forest Night",
    subtext: "Crickets and nighttime forest ambiance",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Fall asleep to the sounds of a serene forest night.",
    type: "audio",
  },
  {
    title: "Seaside Serenity",
    subtext: "Calming ocean waves",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of the sea.",
    type: "audio",
  },
  {
    title: "Summer Meadow",
    subtext: "Birds and gentle breezes",
    duration: "15:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the sounds of a peaceful summer meadow.",
    type: "audio",
  },
  {
    title: "Desert Wind",
    subtext: "Whispering winds and distant calls",
    duration: "13:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the vastness of the desert through sound.",
    type: "audio",
  },
  {
    title: "Morning Coffee Jazz",
    subtext: "Smooth jazz for your morning routine with relaxing jazz melodies. melodies. melodies. melodies.",
    duration: "19:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Start your day with relaxing jazz melodies.",
    type: "audio",
  },
  {
    title: "Classical Piano Solitude",
    subtext: "Reflective piano pieces",
    duration: "17:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy calming classical piano music.",
    type: "audio",
  },
  {
    title: "Ambient Space Journey",
    subtext: "Explore the cosmos with ambient sounds",
    duration: "21:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Take a journey through space with ambient soundscapes.",
    type: "audio",
  },
  {
    title: "Relaxing Wind Chimes",
    subtext: "Soothing chime melodies",
    duration: "14:45",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Calm your mind with the gentle sounds of wind chimes.",
    type: "audio",
  },
  {
    title: "Mindful Breathing Exercise",
    subtext: "Guided breathing for relaxation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Follow a guided breathing exercise to relax and center yourself.",
    type: "audio",
  },
  {
    title: "Mystic Flute",
    subtext: "Enchanting flute music",
    duration: "18:05",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Let the mystical sounds of the flute transport you.",
    type: "audio",
  },
  {
    title: "Zen Garden",
    subtext: "Japanese garden ambiance",
    duration: "22:10",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a Zen garden.",
    type: "audio",
  },
  {
    title: "Thunderstorm Relaxation",
    subtext: "Storm sounds for deep relaxation",
    duration: "26:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Unwind with the powerful and soothing sounds of a thunderstorm.",
    type: "audio",
  },
  {
    title: "Morning Birdsong",
    subtext: "Chirping birds to start your day",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the cheerful sounds of morning birdsong.",
    type: "audio",
  },
  {
    title: "Healing Tibetan Bowls",
    subtext: "Sound therapy with Tibetan bowls",
    duration: "14:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Experience deep relaxation with Tibetan bowl sounds.",
    type: "audio",
  },
  {
    title: "Nature Walk",
    subtext: "Walk through various nature scenes",
    duration: "23:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Take a virtual walk through diverse natural environments.",
    type: "audio",
  },
  {
    title: "Autumn Leaves",
    subtext: "Crunching leaves and cool breezes",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn day.",
    type: "audio",
  },
  {
    title: "Guided Sleep Meditation",
    subtext: "Narrated meditation for better sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into sleep with a calming guided meditation.",
    type: "audio",
  },
  {
    title: "Calm Piano",
    subtext: "Relaxing piano music",
    duration: "16:40",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy soothing piano pieces for relaxation.",
    type: "audio",
  },
  {
    title: "Peaceful Morning",
    subtext: "Gentle sounds to start your day",
    duration: "12:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Begin your day with peaceful nature sounds.",
    type: "audio",
  },
  {
    title: "Mountain Echoes",
    subtext: "Nature sounds with distant echoes",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the expanse of the mountains with echoing nature sounds.",
    type: "audio",
  },
  {
    title: "Quiet Library",
    subtext: "Subtle ambiance of a quiet library",
    duration: "20:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the calm and focused atmosphere of a library.",
    type: "audio",
  },
  {
    title: "Sunset Beach",
    subtext: "Waves and distant seabirds",
    duration: "19:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the tranquil sounds of a beach at sunset.",
    type: "audio",
  },
  {
    title: "Midnight Forest",
    subtext: "Nighttime forest ambiance",
    duration: "24:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of the forest at midnight.",
    type: "audio",
  },
  {
    title: "Morning Meditation",
    subtext: "Start your day with guided meditation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Begin your morning with a refreshing guided meditation.",
    type: "audio",
  },
  {
    title: "Windy Plains",
    subtext: "Strong winds over open fields",
    duration: "15:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the power of nature with the sounds of windy plains.",
    type: "audio",
  },
  {
    title: "Soft Guitar",
    subtext: "Gentle acoustic guitar",
    duration: "17:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Relax with soothing acoustic guitar melodies.",
    type: "audio",
  },
  {
    title: "Forest Waterfall",
    subtext: "Waterfall in the heart of the forest",
    duration: "18:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the calming sound of a forest waterfall.",
    type: "audio",
  },
  {
    title: "Calming River",
    subtext: "Gentle river flow",
    duration: "14:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sound of a flowing river.",
    type: "audio",
  },
  {
    title: "Ocean Bliss",
    subtext: "Relaxing ocean sounds",
    duration: "21:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the soothing sounds of the ocean.",
    type: "audio",
  },
  {
    title: "Autumn Brook",
    subtext: "Gentle stream in the fall",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a gentle brook in autumn.",
    type: "audio",
  },
  {
    title: "Urban Rain",
    subtext: "Rain in the city",
    duration: "19:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the sound of rain falling in an urban environment.",
    type: "audio",
  },
  {
    title: "Sunny Field",
    subtext: "Birds and breeze in a sunny field",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the warm and peaceful sounds of a sunny field.",
    type: "audio",
  },
  {
    title: "Winter Wind",
    subtext: "Chilly wind sounds",
    duration: "14:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Experience the calm of a cold winter wind.",
    type: "audio",
  },
  {
    title: "Birdsong Symphony",
    subtext: "Melodic birdsong",
    duration: "13:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with a symphony of birdsong.",
    type: "audio",
  },
  {
    title: "Island Breeze",
    subtext: "Tropical island sounds",
    duration: "20:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Transport yourself to a tropical island with calming sounds.",
    type: "audio",
  },
  {
    title: "Evening Crickets",
    subtext: "Nighttime cricket sounds",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of crickets on a warm evening.",
    type: "audio",
  },
  {
    title: "Deep Cave Echoes",
    subtext: "Eerie cave sounds",
    duration: "21:20",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Explore the depths of a cave with echoing sounds.",
    type: "audio",
  },
  {
    title: "Quiet Meadow",
    subtext: "Peaceful meadow ambiance",
    duration: "16:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a quiet meadow.",
    type: "audio",
  },
  {
    title: "Yoga Nidra",
    subtext: "Guided yoga nidra meditation",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Experience deep relaxation with a guided yoga nidra practice.",
    type: "audio",
  },
  {
    title: "Forest Brook",
    subtext: "Stream in a dense forest",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of a gentle brook in a dense forest.",
    type: "audio",
  },
  {
    title: "Ocean Sunset",
    subtext: "Calm waves at sunset",
    duration: "22:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of ocean waves at sunset.",
    type: "audio",
  },
  {
    title: "Serene Countryside",
    subtext: "Sounds of the countryside",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of the countryside.",
    type: "audio",
  },
  {
    title: "Evening Storm",
    subtext: "Thunder and rain",
    duration: "25:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the sounds of an evening storm.",
    type: "audio",
  },
  {
    title: "Tropical Rainforest",
    subtext: "Rainforest ambiance",
    duration: "21:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the sounds of a tropical rainforest.",
    type: "audio",
  },
  {
    title: "Calm River",
    subtext: "Flowing river sounds",
    duration: "14:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a flowing river.",
    type: "audio",
  },
  {
    title: "Mountain Wind",
    subtext: "Windy mountain ambiance",
    duration: "17:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the power of mountain winds with this calming soundscape.",
    type: "audio",
  },
  {
    title: "Forest Awakening",
    subtext: "Morning sounds in the forest",
    duration: "15:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the serene sounds of a forest morning.",
    type: "audio",
  },
  {
    title: "Rainforest Meditation",
    subtext: "Guided meditation in the rainforest",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Relax deeply with a guided meditation set in a rainforest.",
    type: "audio",
  },
  {
    title: "Snowy Forest",
    subtext: "Winter forest sounds",
    duration: "20:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a snowy forest.",
    type: "audio",
  },
  {
    title: "Calm Sea",
    subtext: "Gentle waves and sea breeze",
    duration: "18:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a gentle sea.",
    type: "audio",
  },
  {
    title: "Deep Sleep Meditation",
    subtext: "Guided meditation for deep sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into deep sleep with this guided meditation.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Calming ocean breeze",
    duration: "16:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Mountain Lake",
    subtext: "Serene mountain lake",
    duration: "18:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the peaceful sounds of a mountain lake.",
    type: "audio",
  },
  {
    title: "Evening Birds",
    subtext: "Birds singing in the evening",
    duration: "17:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of birds singing in the evening.",
    type: "audio",
  },
  {
    title: "Gentle Breeze",
    subtext: "Soft wind sounds",
    duration: "14:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a soft breeze.",
    type: "audio",
  },
  {
    title: "Midnight Rain",
    subtext: "Rainfall at midnight",
    duration: "19:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace with the sound of rainfall at midnight.",
    type: "audio",
  },
  {
    title: "Winter Night",
    subtext: "Quiet winter night sounds",
    duration: "16:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a winter night.",
    type: "audio",
  },
  {
    title: "Ocean Night",
    subtext: "Calming ocean at night",
    duration: "20:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the ocean at night.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing mountain stream",
    duration: "13:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Sunny Garden",
    subtext: "Birds and bees in a sunny garden",
    duration: "15:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the peaceful sounds of a sunny garden.",
    type: "audio",
  },
  {
    title: "Autumn Wind",
    subtext: "Crisp autumn wind",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn wind.",
    type: "audio",
  },
  {
    title: "Evening Sea",
    subtext: "Calm sea in the evening",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the evening sea.",
    type: "audio",
  },
  {
    title: "Winter Forest",
    subtext: "Cold forest sounds",
    duration: "19:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a winter forest.",
    type: "audio",
  },
  {
    title: "Summer Rain",
    subtext: "Gentle summer rain",
    duration: "16:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the gentle sounds of a summer rain.",
    type: "audio",
  },
  {
    title: "Peaceful Meadow",
    subtext: "Serene meadow sounds",
    duration: "17:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a serene meadow.",
    type: "audio",
  },
  {
    title: "Evening Calm",
    subtext: "Relaxing evening sounds",
    duration: "18:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a calm evening.",
    type: "audio",
  },
  {
    title: "Spring Forest",
    subtext: "Springtime forest sounds",
    duration: "16:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a forest in spring.",
    type: "audio",
  },
  {
    title: "Ocean Waves",
    subtext: "Gentle waves on the shore",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of gentle ocean waves.",
    type: "audio",
  },
  {
    title: "Winter Breeze",
    subtext: "Chilly breeze sounds",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a chilly winter breeze.",
    type: "audio",
  },
  {
    title: "Serene Morning",
    subtext: "Calm morning sounds",
    duration: "18:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Start your day with the serene sounds of a calm morning.",
    type: "audio",
  },
  {
    title: "Autumn Rain",
    subtext: "Rain in the fall",
    duration: "17:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the fall.",
    type: "audio",
  },
  {
    title: "Morning Stream",
    subtext: "Gentle stream in the morning",
    duration: "14:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a morning stream.",
    type: "audio",
  },
  {
    title: "Evening Thunderstorm",
    subtext: "Powerful evening storm",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the powerful sounds of an evening thunderstorm.",
    type: "audio",
  },
  {
    title: "Mountain Rain",
    subtext: "Rain in the mountains",
    duration: "19:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the mountains.",
    type: "audio",
  },
  {
    title: "Morning Birds",
    subtext: "Chirping birds in the morning",
    duration: "13:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the cheerful sounds of morning birds.",
    type: "audio",
  },
  {
    title: "Evening Stream",
    subtext: "Gentle stream in the evening",
    duration: "16:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of an evening stream.",
    type: "audio",
  },
  {
    title: "Summer Night",
    subtext: "Night sounds in summer",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a summer night.",
    type: "audio",
  },
  {
    title: "Spring Rain",
    subtext: "Gentle rain in spring",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of gentle spring rain.",
    type: "audio",
  },
  {
    title: "Morning Dew",
    subtext: "Morning sounds with dew",
    duration: "17:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the fresh sounds of morning dew.",
    type: "audio",
  },
  {
    title: "Night Forest",
    subtext: "Forest sounds at night",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a forest at night.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Gentle ocean breeze",
    duration: "14:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Winter Calm",
    subtext: "Calm winter sounds",
    duration: "16:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a calm winter day.",
    type: "audio",
  },
  {
    title: "Spring Meadow",
    subtext: "Meadow sounds in spring",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the fresh sounds of a spring meadow.",
    type: "audio",
  },
  {
    title: "Tranquil Dawn Chorus",
    subtext: "Gentle birdsong for mindful mornings",
    duration: "10:32",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up peacefully with the sounds of the forest.",
    type: "audio",
  },
  {
    title: "Deep Ocean Meditation",
    subtext: "Dive into tranquility with whale song",
    duration: "15:00",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the calming depths of the ocean.",
    type: "audio",
  },
  {
    title: "Floating Among the Clouds",
    subtext: "Ambient music for deep relaxation",
    duration: "22:48",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Drift away with ethereal melodies and soothing harmonies.",
    type: "audio",
  },
  {
    title: "Guided Mindfulness Practice",
    subtext: "Find your center with gentle narration",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Cultivate inner peace through mindful awareness.",
    type: "audio",
  },
  {
    title: "Rainy Afternoon",
    subtext: "Soothing rain sounds",
    duration: "25:12",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of gentle rain.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing water and nature sounds",
    duration: "12:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Listen to the peaceful sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Forest Night",
    subtext: "Crickets and nighttime forest ambiance",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Fall asleep to the sounds of a serene forest night.",
    type: "audio",
  },
  {
    title: "Seaside Serenity",
    subtext: "Calming ocean waves",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of the sea.",
    type: "audio",
  },
  {
    title: "Summer Meadow",
    subtext: "Birds and gentle breezes",
    duration: "15:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the sounds of a peaceful summer meadow.",
    type: "audio",
  },
  {
    title: "Desert Wind",
    subtext: "Whispering winds and distant calls",
    duration: "13:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the vastness of the desert through sound.",
    type: "audio",
  },
  {
    title: "Morning Coffee Jazz",
    subtext: "Smooth jazz for your morning routine",
    duration: "19:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Start your day with relaxing jazz melodies.",
    type: "audio",
  },
  {
    title: "Classical Piano Solitude",
    subtext: "Reflective piano pieces",
    duration: "17:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy calming classical piano music.",
    type: "audio",
  },
  {
    title: "Ambient Space Journey",
    subtext: "Explore the cosmos with ambient sounds",
    duration: "21:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Take a journey through space with ambient soundscapes.",
    type: "audio",
  },
  {
    title: "Relaxing Wind Chimes",
    subtext: "Soothing chime melodies",
    duration: "14:45",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Calm your mind with the gentle sounds of wind chimes.",
    type: "audio",
  },
  {
    title: "Mindful Breathing Exercise",
    subtext: "Guided breathing for relaxation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Follow a guided breathing exercise to relax and center yourself.",
    type: "audio",
  },
  {
    title: "Mystic Flute",
    subtext: "Enchanting flute music",
    duration: "18:05",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Let the mystical sounds of the flute transport you.",
    type: "audio",
  },
  {
    title: "Zen Garden",
    subtext: "Japanese garden ambiance",
    duration: "22:10",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a Zen garden.",
    type: "audio",
  },
  {
    title: "Thunderstorm Relaxation",
    subtext: "Storm sounds for deep relaxation",
    duration: "26:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Unwind with the powerful and soothing sounds of a thunderstorm.",
    type: "audio",
  },
  {
    title: "Morning Birdsong",
    subtext: "Chirping birds to start your day",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the cheerful sounds of morning birdsong.",
    type: "audio",
  },
  {
    title: "Healing Tibetan Bowls",
    subtext: "Sound therapy with Tibetan bowls",
    duration: "14:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Experience deep relaxation with Tibetan bowl sounds.",
    type: "audio",
  },
  {
    title: "Nature Walk",
    subtext: "Walk through various nature scenes",
    duration: "23:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Take a virtual walk through diverse natural environments.",
    type: "audio",
  },
  {
    title: "Autumn Leaves",
    subtext: "Crunching leaves and cool breezes",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn day.",
    type: "audio",
  },
  {
    title: "Guided Sleep Meditation",
    subtext: "Narrated meditation for better sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into sleep with a calming guided meditation.",
    type: "audio",
  },
  {
    title: "Calm Piano",
    subtext: "Relaxing piano music",
    duration: "16:40",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy soothing piano pieces for relaxation.",
    type: "audio",
  },
  {
    title: "Peaceful Morning",
    subtext: "Gentle sounds to start your day",
    duration: "12:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Begin your day with peaceful nature sounds.",
    type: "audio",
  },
  {
    title: "Mountain Echoes",
    subtext: "Nature sounds with distant echoes",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the expanse of the mountains with echoing nature sounds.",
    type: "audio",
  },
  {
    title: "Quiet Library",
    subtext: "Subtle ambiance of a quiet library",
    duration: "20:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the calm and focused atmosphere of a library.",
    type: "audio",
  },
  {
    title: "Sunset Beach",
    subtext: "Waves and distant seabirds",
    duration: "19:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the tranquil sounds of a beach at sunset.",
    type: "audio",
  },
  {
    title: "Midnight Forest",
    subtext: "Nighttime forest ambiance",
    duration: "24:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of the forest at midnight.",
    type: "audio",
  },
  {
    title: "Morning Meditation",
    subtext: "Start your day with guided meditation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Begin your morning with a refreshing guided meditation.",
    type: "audio",
  },
  {
    title: "Windy Plains",
    subtext: "Strong winds over open fields",
    duration: "15:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the power of nature with the sounds of windy plains.",
    type: "audio",
  },
  {
    title: "Soft Guitar",
    subtext: "Gentle acoustic guitar",
    duration: "17:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Relax with soothing acoustic guitar melodies.",
    type: "audio",
  },
  {
    title: "Forest Waterfall",
    subtext: "Waterfall in the heart of the forest",
    duration: "18:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the calming sound of a forest waterfall.",
    type: "audio",
  },
  {
    title: "Calming River",
    subtext: "Gentle river flow",
    duration: "14:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sound of a flowing river.",
    type: "audio",
  },
  {
    title: "Ocean Bliss",
    subtext: "Relaxing ocean sounds",
    duration: "21:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the soothing sounds of the ocean.",
    type: "audio",
  },
  {
    title: "Autumn Brook",
    subtext: "Gentle stream in the fall",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a gentle brook in autumn.",
    type: "audio",
  },
  {
    title: "Urban Rain",
    subtext: "Rain in the city",
    duration: "19:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the sound of rain falling in an urban environment.",
    type: "audio",
  },
  {
    title: "Sunny Field",
    subtext: "Birds and breeze in a sunny field",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the warm and peaceful sounds of a sunny field.",
    type: "audio",
  },
  {
    title: "Winter Wind",
    subtext: "Chilly wind sounds",
    duration: "14:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Experience the calm of a cold winter wind.",
    type: "audio",
  },
  {
    title: "Birdsong Symphony",
    subtext: "Melodic birdsong",
    duration: "13:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with a symphony of birdsong.",
    type: "audio",
  },
  {
    title: "Island Breeze",
    subtext: "Tropical island sounds",
    duration: "20:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Transport yourself to a tropical island with calming sounds.",
    type: "audio",
  },
  {
    title: "Evening Crickets",
    subtext: "Nighttime cricket sounds",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of crickets on a warm evening.",
    type: "audio",
  },
  {
    title: "Deep Cave Echoes",
    subtext: "Eerie cave sounds",
    duration: "21:20",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Explore the depths of a cave with echoing sounds.",
    type: "audio",
  },
  {
    title: "Quiet Meadow",
    subtext: "Peaceful meadow ambiance",
    duration: "16:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a quiet meadow.",
    type: "audio",
  },
  {
    title: "Yoga Nidra",
    subtext: "Guided yoga nidra meditation",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Experience deep relaxation with a guided yoga nidra practice.",
    type: "audio",
  },
  {
    title: "Forest Brook",
    subtext: "Stream in a dense forest",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of a gentle brook in a dense forest.",
    type: "audio",
  },
  {
    title: "Ocean Sunset",
    subtext: "Calm waves at sunset",
    duration: "22:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of ocean waves at sunset.",
    type: "audio",
  },
  {
    title: "Serene Countryside",
    subtext: "Sounds of the countryside",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of the countryside.",
    type: "audio",
  },
  {
    title: "Evening Storm",
    subtext: "Thunder and rain",
    duration: "25:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the sounds of an evening storm.",
    type: "audio",
  },
  {
    title: "Tropical Rainforest",
    subtext: "Rainforest ambiance",
    duration: "21:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the sounds of a tropical rainforest.",
    type: "audio",
  },
  {
    title: "Calm River",
    subtext: "Flowing river sounds",
    duration: "14:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a flowing river.",
    type: "audio",
  },
  {
    title: "Mountain Wind",
    subtext: "Windy mountain ambiance",
    duration: "17:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the power of mountain winds with this calming soundscape.",
    type: "audio",
  },
  {
    title: "Forest Awakening",
    subtext: "Morning sounds in the forest",
    duration: "15:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the serene sounds of a forest morning.",
    type: "audio",
  },
  {
    title: "Rainforest Meditation",
    subtext: "Guided meditation in the rainforest",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Relax deeply with a guided meditation set in a rainforest.",
    type: "audio",
  },
  {
    title: "Snowy Forest",
    subtext: "Winter forest sounds",
    duration: "20:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a snowy forest.",
    type: "audio",
  },
  {
    title: "Calm Sea",
    subtext: "Gentle waves and sea breeze",
    duration: "18:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a gentle sea.",
    type: "audio",
  },
  {
    title: "Deep Sleep Meditation",
    subtext: "Guided meditation for deep sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into deep sleep with this guided meditation.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Calming ocean breeze",
    duration: "16:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Mountain Lake",
    subtext: "Serene mountain lake",
    duration: "18:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the peaceful sounds of a mountain lake.",
    type: "audio",
  },
  {
    title: "Evening Birds",
    subtext: "Birds singing in the evening",
    duration: "17:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of birds singing in the evening.",
    type: "audio",
  },
  {
    title: "Gentle Breeze",
    subtext: "Soft wind sounds",
    duration: "14:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a soft breeze.",
    type: "audio",
  },
  {
    title: "Midnight Rain",
    subtext: "Rainfall at midnight",
    duration: "19:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace with the sound of rainfall at midnight.",
    type: "audio",
  },
  {
    title: "Winter Night",
    subtext: "Quiet winter night sounds",
    duration: "16:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a winter night.",
    type: "audio",
  },
  {
    title: "Ocean Night",
    subtext: "Calming ocean at night",
    duration: "20:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the ocean at night.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing mountain stream",
    duration: "13:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Sunny Garden",
    subtext: "Birds and bees in a sunny garden",
    duration: "15:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the peaceful sounds of a sunny garden.",
    type: "audio",
  },
  {
    title: "Autumn Wind",
    subtext: "Crisp autumn wind",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn wind.",
    type: "audio",
  },
  {
    title: "Evening Sea",
    subtext: "Calm sea in the evening",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the evening sea.",
    type: "audio",
  },
  {
    title: "Winter Forest",
    subtext: "Cold forest sounds",
    duration: "19:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a winter forest.",
    type: "audio",
  },
  {
    title: "Summer Rain",
    subtext: "Gentle summer rain",
    duration: "16:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the gentle sounds of a summer rain.",
    type: "audio",
  },
  {
    title: "Peaceful Meadow",
    subtext: "Serene meadow sounds",
    duration: "17:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a serene meadow.",
    type: "audio",
  },
  {
    title: "Evening Calm",
    subtext: "Relaxing evening sounds",
    duration: "18:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a calm evening.",
    type: "audio",
  },
  {
    title: "Spring Forest",
    subtext: "Springtime forest sounds",
    duration: "16:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a forest in spring.",
    type: "audio",
  },
  {
    title: "Ocean Waves",
    subtext: "Gentle waves on the shore",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of gentle ocean waves.",
    type: "audio",
  },
  {
    title: "Winter Breeze",
    subtext: "Chilly breeze sounds",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a chilly winter breeze.",
    type: "audio",
  },
  {
    title: "Serene Morning",
    subtext: "Calm morning sounds",
    duration: "18:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Start your day with the serene sounds of a calm morning.",
    type: "audio",
  },
  {
    title: "Autumn Rain",
    subtext: "Rain in the fall",
    duration: "17:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the fall.",
    type: "audio",
  },
  {
    title: "Morning Stream",
    subtext: "Gentle stream in the morning",
    duration: "14:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a morning stream.",
    type: "audio",
  },
  {
    title: "Evening Thunderstorm",
    subtext: "Powerful evening storm",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the powerful sounds of an evening thunderstorm.",
    type: "audio",
  },
  {
    title: "Mountain Rain",
    subtext: "Rain in the mountains",
    duration: "19:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the mountains.",
    type: "audio",
  },
  {
    title: "Morning Birds",
    subtext: "Chirping birds in the morning",
    duration: "13:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the cheerful sounds of morning birds.",
    type: "audio",
  },
  {
    title: "Evening Stream",
    subtext: "Gentle stream in the evening",
    duration: "16:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of an evening stream.",
    type: "audio",
  },
  {
    title: "Summer Night",
    subtext: "Night sounds in summer",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a summer night.",
    type: "audio",
  },
  {
    title: "Spring Rain",
    subtext: "Gentle rain in spring",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of gentle spring rain.",
    type: "audio",
  },
  {
    title: "Morning Dew",
    subtext: "Morning sounds with dew",
    duration: "17:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the fresh sounds of morning dew.",
    type: "audio",
  },
  {
    title: "Night Forest",
    subtext: "Forest sounds at night",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a forest at night.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Gentle ocean breeze",
    duration: "14:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Winter Calm",
    subtext: "Calm winter sounds",
    duration: "16:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a calm winter day.",
    type: "audio",
  },
  {
    title: "Spring Meadow",
    subtext: "Meadow sounds in spring",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the fresh sounds of a spring meadow.",
    type: "audio",
  },
  {
    title: "Tranquil Dawn Chorus",
    subtext: "Gentle birdsong for mindful mornings",
    duration: "10:32",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up peacefully with the sounds of the forest.",
    type: "audio",
  },
  {
    title: "Deep Ocean Meditation",
    subtext: "Dive into tranquility with whale song",
    duration: "15:00",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the calming depths of the ocean.",
    type: "audio",
  },
  {
    title: "Floating Among the Clouds",
    subtext: "Ambient music for deep relaxation",
    duration: "22:48",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Drift away with ethereal melodies and soothing harmonies.",
    type: "audio",
  },
  {
    title: "Guided Mindfulness Practice",
    subtext: "Find your center with gentle narration",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Cultivate inner peace through mindful awareness.",
    type: "audio",
  },
  {
    title: "Rainy Afternoon",
    subtext: "Soothing rain sounds",
    duration: "25:12",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of gentle rain.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing water and nature sounds",
    duration: "12:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Listen to the peaceful sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Forest Night",
    subtext: "Crickets and nighttime forest ambiance",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Fall asleep to the sounds of a serene forest night.",
    type: "audio",
  },
  {
    title: "Seaside Serenity",
    subtext: "Calming ocean waves",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of the sea.",
    type: "audio",
  },
  {
    title: "Summer Meadow",
    subtext: "Birds and gentle breezes",
    duration: "15:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the sounds of a peaceful summer meadow.",
    type: "audio",
  },
  {
    title: "Desert Wind",
    subtext: "Whispering winds and distant calls",
    duration: "13:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the vastness of the desert through sound.",
    type: "audio",
  },
  {
    title: "Morning Coffee Jazz",
    subtext: "Smooth jazz for your morning routine",
    duration: "19:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Start your day with relaxing jazz melodies.",
    type: "audio",
  },
  {
    title: "Classical Piano Solitude",
    subtext: "Reflective piano pieces",
    duration: "17:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy calming classical piano music.",
    type: "audio",
  },
  {
    title: "Ambient Space Journey",
    subtext: "Explore the cosmos with ambient sounds",
    duration: "21:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Take a journey through space with ambient soundscapes.",
    type: "audio",
  },
  {
    title: "Relaxing Wind Chimes",
    subtext: "Soothing chime melodies",
    duration: "14:45",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Calm your mind with the gentle sounds of wind chimes.",
    type: "audio",
  },
  {
    title: "Mindful Breathing Exercise",
    subtext: "Guided breathing for relaxation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Follow a guided breathing exercise to relax and center yourself.",
    type: "audio",
  },
  {
    title: "Mystic Flute",
    subtext: "Enchanting flute music",
    duration: "18:05",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Let the mystical sounds of the flute transport you.",
    type: "audio",
  },
  {
    title: "Zen Garden",
    subtext: "Japanese garden ambiance",
    duration: "22:10",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a Zen garden.",
    type: "audio",
  },
  {
    title: "Thunderstorm Relaxation",
    subtext: "Storm sounds for deep relaxation",
    duration: "26:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Unwind with the powerful and soothing sounds of a thunderstorm.",
    type: "audio",
  },
  {
    title: "Morning Birdsong",
    subtext: "Chirping birds to start your day",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the cheerful sounds of morning birdsong.",
    type: "audio",
  },
  {
    title: "Healing Tibetan Bowls",
    subtext: "Sound therapy with Tibetan bowls",
    duration: "14:30",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Experience deep relaxation with Tibetan bowl sounds.",
    type: "audio",
  },
  {
    title: "Nature Walk",
    subtext: "Walk through various nature scenes",
    duration: "23:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Take a virtual walk through diverse natural environments.",
    type: "audio",
  },
  {
    title: "Autumn Leaves",
    subtext: "Crunching leaves and cool breezes",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn day.",
    type: "audio",
  },
  {
    title: "Guided Sleep Meditation",
    subtext: "Narrated meditation for better sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into sleep with a calming guided meditation.",
    type: "audio",
  },
  {
    title: "Calm Piano",
    subtext: "Relaxing piano music",
    duration: "16:40",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Enjoy soothing piano pieces for relaxation.",
    type: "audio",
  },
  {
    title: "Peaceful Morning",
    subtext: "Gentle sounds to start your day",
    duration: "12:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Begin your day with peaceful nature sounds.",
    type: "audio",
  },
  {
    title: "Mountain Echoes",
    subtext: "Nature sounds with distant echoes",
    duration: "18:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the expanse of the mountains with echoing nature sounds.",
    type: "audio",
  },
  {
    title: "Quiet Library",
    subtext: "Subtle ambiance of a quiet library",
    duration: "20:15",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Relax with the calm and focused atmosphere of a library.",
    type: "audio",
  },
  {
    title: "Sunset Beach",
    subtext: "Waves and distant seabirds",
    duration: "19:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the tranquil sounds of a beach at sunset.",
    type: "audio",
  },
  {
    title: "Midnight Forest",
    subtext: "Nighttime forest ambiance",
    duration: "24:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of the forest at midnight.",
    type: "audio",
  },
  {
    title: "Morning Meditation",
    subtext: "Start your day with guided meditation",
    duration: "10:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Begin your morning with a refreshing guided meditation.",
    type: "audio",
  },
  {
    title: "Windy Plains",
    subtext: "Strong winds over open fields",
    duration: "15:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Feel the power of nature with the sounds of windy plains.",
    type: "audio",
  },
  {
    title: "Soft Guitar",
    subtext: "Gentle acoustic guitar",
    duration: "17:00",
    category: "instrumental",
    likes: 0,
    listens: 0,
    description: "Relax with soothing acoustic guitar melodies.",
    type: "audio",
  },
  {
    title: "Forest Waterfall",
    subtext: "Waterfall in the heart of the forest",
    duration: "18:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the calming sound of a forest waterfall.",
    type: "audio",
  },
  {
    title: "Calming River",
    subtext: "Gentle river flow",
    duration: "14:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sound of a flowing river.",
    type: "audio",
  },
  {
    title: "Ocean Bliss",
    subtext: "Relaxing ocean sounds",
    duration: "21:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the soothing sounds of the ocean.",
    type: "audio",
  },
  {
    title: "Autumn Brook",
    subtext: "Gentle stream in the fall",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a gentle brook in autumn.",
    type: "audio",
  },
  {
    title: "Urban Rain",
    subtext: "Rain in the city",
    duration: "19:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the sound of rain falling in an urban environment.",
    type: "audio",
  },
  {
    title: "Sunny Field",
    subtext: "Birds and breeze in a sunny field",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the warm and peaceful sounds of a sunny field.",
    type: "audio",
  },
  {
    title: "Winter Wind",
    subtext: "Chilly wind sounds",
    duration: "14:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Experience the calm of a cold winter wind.",
    type: "audio",
  },
  {
    title: "Birdsong Symphony",
    subtext: "Melodic birdsong",
    duration: "13:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with a symphony of birdsong.",
    type: "audio",
  },
  {
    title: "Island Breeze",
    subtext: "Tropical island sounds",
    duration: "20:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Transport yourself to a tropical island with calming sounds.",
    type: "audio",
  },
  {
    title: "Evening Crickets",
    subtext: "Nighttime cricket sounds",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of crickets on a warm evening.",
    type: "audio",
  },
  {
    title: "Deep Cave Echoes",
    subtext: "Eerie cave sounds",
    duration: "21:20",
    category: "soundscape",
    likes: 0,
    listens: 0,
    description: "Explore the depths of a cave with echoing sounds.",
    type: "audio",
  },
  {
    title: "Quiet Meadow",
    subtext: "Peaceful meadow ambiance",
    duration: "16:05",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a quiet meadow.",
    type: "audio",
  },
  {
    title: "Yoga Nidra",
    subtext: "Guided yoga nidra meditation",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description:
      "Experience deep relaxation with a guided yoga nidra practice.",
    type: "audio",
  },
  {
    title: "Forest Brook",
    subtext: "Stream in a dense forest",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sound of a gentle brook in a dense forest.",
    type: "audio",
  },
  {
    title: "Ocean Sunset",
    subtext: "Calm waves at sunset",
    duration: "22:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of ocean waves at sunset.",
    type: "audio",
  },
  {
    title: "Serene Countryside",
    subtext: "Sounds of the countryside",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of the countryside.",
    type: "audio",
  },
  {
    title: "Evening Storm",
    subtext: "Thunder and rain",
    duration: "25:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the sounds of an evening storm.",
    type: "audio",
  },
  {
    title: "Tropical Rainforest",
    subtext: "Rainforest ambiance",
    duration: "21:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Immerse yourself in the sounds of a tropical rainforest.",
    type: "audio",
  },
  {
    title: "Calm River",
    subtext: "Flowing river sounds",
    duration: "14:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a flowing river.",
    type: "audio",
  },
  {
    title: "Mountain Wind",
    subtext: "Windy mountain ambiance",
    duration: "17:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Feel the power of mountain winds with this calming soundscape.",
    type: "audio",
  },
  {
    title: "Forest Awakening",
    subtext: "Morning sounds in the forest",
    duration: "15:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the serene sounds of a forest morning.",
    type: "audio",
  },
  {
    title: "Rainforest Meditation",
    subtext: "Guided meditation in the rainforest",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Relax deeply with a guided meditation set in a rainforest.",
    type: "audio",
  },
  {
    title: "Snowy Forest",
    subtext: "Winter forest sounds",
    duration: "20:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a snowy forest.",
    type: "audio",
  },
  {
    title: "Calm Sea",
    subtext: "Gentle waves and sea breeze",
    duration: "18:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a gentle sea.",
    type: "audio",
  },
  {
    title: "Deep Sleep Meditation",
    subtext: "Guided meditation for deep sleep",
    duration: "30:00",
    category: "guided",
    likes: 0,
    listens: 0,
    description: "Ease into deep sleep with this guided meditation.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Calming ocean breeze",
    duration: "16:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Mountain Lake",
    subtext: "Serene mountain lake",
    duration: "18:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the peaceful sounds of a mountain lake.",
    type: "audio",
  },
  {
    title: "Evening Birds",
    subtext: "Birds singing in the evening",
    duration: "17:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of birds singing in the evening.",
    type: "audio",
  },
  {
    title: "Gentle Breeze",
    subtext: "Soft wind sounds",
    duration: "14:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the gentle sounds of a soft breeze.",
    type: "audio",
  },
  {
    title: "Midnight Rain",
    subtext: "Rainfall at midnight",
    duration: "19:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace with the sound of rainfall at midnight.",
    type: "audio",
  },
  {
    title: "Winter Night",
    subtext: "Quiet winter night sounds",
    duration: "16:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the serene sounds of a winter night.",
    type: "audio",
  },
  {
    title: "Ocean Night",
    subtext: "Calming ocean at night",
    duration: "20:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the ocean at night.",
    type: "audio",
  },
  {
    title: "Mountain Stream",
    subtext: "Flowing mountain stream",
    duration: "13:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of a mountain stream.",
    type: "audio",
  },
  {
    title: "Sunny Garden",
    subtext: "Birds and bees in a sunny garden",
    duration: "15:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the peaceful sounds of a sunny garden.",
    type: "audio",
  },
  {
    title: "Autumn Wind",
    subtext: "Crisp autumn wind",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a crisp autumn wind.",
    type: "audio",
  },
  {
    title: "Evening Sea",
    subtext: "Calm sea in the evening",
    duration: "18:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of the evening sea.",
    type: "audio",
  },
  {
    title: "Winter Forest",
    subtext: "Cold forest sounds",
    duration: "19:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a winter forest.",
    type: "audio",
  },
  {
    title: "Summer Rain",
    subtext: "Gentle summer rain",
    duration: "16:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Find peace in the gentle sounds of a summer rain.",
    type: "audio",
  },
  {
    title: "Peaceful Meadow",
    subtext: "Serene meadow sounds",
    duration: "17:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax in the peaceful ambiance of a serene meadow.",
    type: "audio",
  },
  {
    title: "Evening Calm",
    subtext: "Relaxing evening sounds",
    duration: "18:15",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a calm evening.",
    type: "audio",
  },
  {
    title: "Spring Forest",
    subtext: "Springtime forest sounds",
    duration: "16:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a forest in spring.",
    type: "audio",
  },
  {
    title: "Ocean Waves",
    subtext: "Gentle waves on the shore",
    duration: "15:10",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of gentle ocean waves.",
    type: "audio",
  },
  {
    title: "Winter Breeze",
    subtext: "Chilly breeze sounds",
    duration: "14:50",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the sounds of a chilly winter breeze.",
    type: "audio",
  },
  {
    title: "Serene Morning",
    subtext: "Calm morning sounds",
    duration: "18:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Start your day with the serene sounds of a calm morning.",
    type: "audio",
  },
  {
    title: "Autumn Rain",
    subtext: "Rain in the fall",
    duration: "17:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the fall.",
    type: "audio",
  },
  {
    title: "Morning Stream",
    subtext: "Gentle stream in the morning",
    duration: "14:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the calming sounds of a morning stream.",
    type: "audio",
  },
  {
    title: "Evening Thunderstorm",
    subtext: "Powerful evening storm",
    duration: "20:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description:
      "Find peace in the powerful sounds of an evening thunderstorm.",
    type: "audio",
  },
  {
    title: "Mountain Rain",
    subtext: "Rain in the mountains",
    duration: "19:00",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the soothing sounds of rain in the mountains.",
    type: "audio",
  },
  {
    title: "Morning Birds",
    subtext: "Chirping birds in the morning",
    duration: "13:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the cheerful sounds of morning birds.",
    type: "audio",
  },
  {
    title: "Evening Stream",
    subtext: "Gentle stream in the evening",
    duration: "16:45",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of an evening stream.",
    type: "audio",
  },
  {
    title: "Summer Night",
    subtext: "Night sounds in summer",
    duration: "19:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the soothing sounds of a summer night.",
    type: "audio",
  },
  {
    title: "Spring Rain",
    subtext: "Gentle rain in spring",
    duration: "15:25",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the calming sounds of gentle spring rain.",
    type: "audio",
  },
  {
    title: "Morning Dew",
    subtext: "Morning sounds with dew",
    duration: "17:30",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Wake up with the fresh sounds of morning dew.",
    type: "audio",
  },
  {
    title: "Night Forest",
    subtext: "Forest sounds at night",
    duration: "18:40",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a forest at night.",
    type: "audio",
  },
  {
    title: "Ocean Breeze",
    subtext: "Gentle ocean breeze",
    duration: "14:55",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Unwind with the gentle sounds of an ocean breeze.",
    type: "audio",
  },
  {
    title: "Winter Calm",
    subtext: "Calm winter sounds",
    duration: "16:35",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Relax with the peaceful sounds of a calm winter day.",
    type: "audio",
  },
  {
    title: "Spring Meadow",
    subtext: "Meadow sounds in spring",
    duration: "17:20",
    category: "nature",
    likes: 0,
    listens: 0,
    description: "Enjoy the fresh sounds of a spring meadow.",
    type: "audio",
  },
];

export const HomeScreenData = AudioData.slice(0, 12)
export const SleepScreenData = AudioData.slice(13, 21)
export const MeditateScreenData = AudioData.slice(22, 160)
export const MuiscScreenData = AudioData.slice(161, 267)
